name: CI Testing 

on:
  push:
    branches:
      - main
    tags: ['*']

  pull_request:


jobs: 
  build: 

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install package dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run Unit Tests and Collect Coverage
        run: |
          python -m pip install coverage[toml]
          pytest --cov=odepy --cov-report=xml tests/

      - name: Upload Coverage to Codecov 
        uses: codecov/codecov-action@v3
        with: 
          token: 02c4a184-abc7-432d-800b-3ef00c132eb5